### ISSUE TITLE
EventException on first time gamemode change after MV-inv import

### ISSUE THREAD

**Issue by elFlashor** [Gnat008/PerWorldInventory#101]
Steps to reproduce:
1 - Use "/pwi convert multiverse" to import data from MV-inv
2 - Stop the server, remove MV-inv (*ahem* ^^) , restart the server
3 - Log on, and change to a gamemode you never used before on the server (ex: spectator, or creative works too for players that never used it)

The following error is logged to the console:
`[21:21:28] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.8.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:66) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	at me.gnat008.perworldinventory.data.FileWriter.getFromDatabase(FileWriter.java:145) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:155) ~[?:?]
	at me.gnat008.perworldinventory.process.GameModeChangeProcess.processGameModeChange(GameModeChangeProcess.java:58) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerGameModeChangeListener.onPlayerGameModeChange(PlayerGameModeChangeListener.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
	... 24 more`

All the following times you change gamemode, no error is logged and the plugin works as intended. It only have that error the very first time.

**Comment by Gnat008** [comment]
Do you happen to have the data file for a player where this problem will occur? I guess that would be for the gamemode the player hasn't changed to yet.

**Comment by elFlashor** [comment]
I suppose you're referring to the PWI data?

**Comment by Gnat008** [comment]
Yeah.

**Comment by elFlashor** [comment]
Here are the data of two players.

[Never used creative or spectator.zip](https://github.com/Gnat008/PerWorldInventory/files/455558/Never.used.creative.or.spectator.zip)
[Never used creative, spectator or adventure.zip](https://github.com/Gnat008/PerWorldInventory/files/455559/Never.used.creative.spectator.or.adventure.zip)

From what I've quickly seen it seems the files are empty before using a gamemode for the first time, and are not after...?

**Comment by Gnat008** [comment]
Are you using a test server? If so, could I get you to try to delete all the player data in PWI, and reimport from MV-I using this jar? Then see if there are any further issues.
https://www.dropbox.com/s/us787tf44xspspm/perworldinventory-1.8.2.jar?dl=0

**Comment by elFlashor** [comment]
This version has fixed the issue and I see no error in the console anymore.
