### ISSUE TITLE
Dependency with GroupManager

### ISSUE THREAD

**Issue by carlosplanchon** [Gnat008/PerWorldInventory#104]
Hi when I try to start ur plugin it throws this error:
(I'm not GM user (I'm using zPerms))
That's the traceback:
    [17:03:24 ERROR]: Error occurred while enabling PerWorldInventory v1.8.2 (Is it up to date?)
    ch.jalu.injector.exceptions.InjectorException: Did not find instantiation method for 'class me.gnat008.perworldinventory.groups.GroupManager'. Make sure your class conforms to one of the registered instantiations. If default: make sure you have a constructor with @Inject or fields with @Inject. Fields with @Inject require the default constructor at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:203) ~[?:?]
    at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:180) ~[?:?]
    at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:162) ~[?:?]
    at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:51) ~[?:?]
    at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:159) ~[?:?]
    at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:124) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

Maybe u may use Vault :P
https://dev.bukkit.org/bukkit-plugins/vault/

**Comment by Gnat008** [comment]
This has nothing to do with dependencies or permissions, its an internal class.

**Comment by Gnat008** [comment]
Moreover, I cannot reproduce this issue. Try redownloading the plugin, and trying again.

**Comment by Oruss7** [comment]
see #106
