### ISSUE TITLE
Error 1.8.2/1.8.1 not find instantiation method

### ISSUE THREAD

**Issue by Oruss7** [Gnat008/PerWorldInventory#106]
```
[20:53:52] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.8.1 (Is it up to date?)
ch.jalu.injector.exceptions.InjectorException: Did not find instantiation method for 'class me.gnat008.perworldinventory.groups.GroupManager'. Make sure your class conforms to one of the registered instantiations. If default: make sure you have a constructor with @Inject or fields with @Inject. Fields with @Inject require the default constructor
	at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:167) ~[?:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:140) ~[?:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:125) ~[?:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:49) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:157) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:122) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar:git-Spigot-1e4dd71-4db0855]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Comment by Oruss7** [comment]
1.8.0 is also bugged

**Comment by Oruss7** [comment]
I use groupManager as perm plugin

**Comment by ljacqu** [comment]
- Was 1.7.x not bugged with this?

Technical analysis: I'm on current master and can't reproduce this; the initialization test also passes... :confused: Do note that the first time an instantiating method from the injector is called is when GroupManager.class should be built, so let's not forget that the problem might not be the GroupManager class itself. Injector looks set up well, though, and as far as I've seen there haven't been any changes to the injector setup lately. (Besides the upgrade from 0.2 to 0.3 five days ago.)

**Comment by carlosplanchon** [comment]
I have problems with the Injector too:
https://github.com/Gnat008/PerWorldInventory/issues/104

**Comment by Oruss7** [comment]
1.7.x working fine.

**Comment by Gnat008** [comment]
As I can recall, the only thing I've done besides updating the Injector was to add the API class. And That should be the last thing instantiated, since it depends on everything else.

**Comment by ljacqu** [comment]
Not home today so can't check—

@Gnat008 can you reproduce this? Like starting the plugin on a server. If so, does it go away with 0.2? I agree that the API addition shouldn't make a difference at all.

**Comment by Gnat008** [comment]
@ljacqu I am also unable to reproduce this, either on my test server, or my live server. I can quickly build a version using version 0.2 of the injector if @Oruss7 and/or @carlosplanchon or anyone else wants to see if it works then.

**Comment by ljacqu** [comment]
@Oruss7 could this be solved? Otherwise we'll provide you a JAR with a previous version of the injector.

**Comment by Oruss7** [comment]
Not reproductible on my test server (exactly the same as production server).

**Comment by ljacqu** [comment]
and the production server still has it?

**Comment by Oruss7** [comment]
Can't test, they are people online. ^^´

**Comment by Oruss7** [comment]
Still persist on my prod server. Strange...

**Comment by Oruss7** [comment]
Solved: update Authme Reloaded.

http://ci.xephi.fr/job/AuthMeReloaded/

**Comment by Gnat008** [comment]
Err.... Ideas, @ljacqu?

**Comment by ljacqu** [comment]
I wonder if this is some weird case where AuthMe and PerWorldInventory had different versions of the injector and somehow that caused a conflict... Hmm. I can't imagine why any version from 0.1 to 0.3 would complain about a simple class using field injection, but you know... :/ Thanks for the feedback, @Oruss7
