### ISSUE TITLE
NullPointerException - PerWorldInventory v1.8.2

### ISSUE THREAD

**Issue by shone-zmaj** [Gnat008/PerWorldInventory#109]
[10:13:43] [Craft Scheduler Thread - 257/WARN]: Exception in thread "Craft Scheduler Thread - 257" 
[10:13:43] [Craft Scheduler Thread - 257/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 26254
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
    at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
    at me.gnat008.perworldinventory.data.FileWriter$$Lambda$6/1231676169.run(Unknown Source)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by Gnat008** [comment]
Hm I am unable to reproduce this on my servers. Could you tell me if this happens to everyone, and/or under what circumstances?

**Comment by shone-zmaj** [comment]
It happens to some players when they come from other worlds created with multiverse into overworld and also this happens sometimes 
[Server thread/ERROR]: [PerWorldInventory] Unable to find inventory data for player 'TheNanglater' for group 'Cherry_Vanilla': plugins\PerWorldInventory\datadefaults\__default.json (The specified path was not found), and group 'Cherry_Vanilla' doesn't exist in worlds file and world named 'Cherry_Vanilla' is in default group, and the file __default.json exists in that path i checked

**Comment by TheJens90** [comment]
I got the same error message. After using /home or /gamemode.

`
[16:36:24] [Server thread/INFO]: ProfDrBielefeld issued server command: /home
[16:39:07] [Craft Scheduler Thread - 7/WARN]: Exception in thread "Craft Scheduler Thread - 7"
[16:39:07] [Craft Scheduler Thread - 7/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 746
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:224)
        at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
        at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
`

**Comment by TheOneWhoKnocks** [comment]
I get the same Errors when changing worlds, changing gamemodes and even totally random without anyone playing on the Server. I'm using the newest version of pwi with spigot 1.10

`[09:03:06] [Server thread/WARN]: [PerWorldInventory] Task #97267 for PerWorldInventory v1.8.3 generated an exception
java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:332) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-570526c-75a8885]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[09:08:06] [Server thread/WARN]: [PerWorldInventory] Task #97267 for PerWorldInventory v1.8.3 generated an exception
java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:332) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-570526c-75a8885]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
`

**Comment by Gnat008** [comment]
This should now be fixed, see #115.
