### ISSUE TITLE
Warn/Error Log in Console if Player disconnects (Log, Warn, Error)

### ISSUE THREAD

**Issue by Ishidres** [Gnat008/PerWorldInventory#120]
Hey there,

first of all some information:

- I'm **not** using Bungeecord
- I'm using **Spigot 1.8.8**

So, if a players disconnects from the server, I'm getting an Error/Warn in Console. Have a look at the Console Log:

`[15:55:22 INFO]:[-] [Player] gamer90018
[15:55:22 WARN]: Exception in thread "Craft Scheduler Thread - 5652" 
[15:55:22 WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 2732131 at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:221) at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88) at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80) at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) ... 3 more`

I hope, I said everything correctly and gave enough information! :smile: 

Best wishes,
Ishidres

**Comment by Ishidres** [comment]
You can also download the log:
