### ISSUE TITLE
Not finding inventory data and generated exception

### ISSUE THREAD

**Issue by PAINmatrix** [Gnat008/PerWorldInventory#122]
I am getting a few different errors doing a few different things. The first one I have not figured out what causes it, but here it is:
`30.09 14:49:32 [Server] WARN Exception in thread "Craft Scheduler Thread - 27" 
30.09 14:49:32 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.2 generated an exception while executing task 2338
30.09 14:49:32 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
30.09 14:49:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
30.09 14:49:32 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
30.09 14:49:32 [Server] INFO at java.lang.Thread.run(Unknown Source)
30.09 14:49:32 [Server] INFO Caused by: java.lang.NullPointerException
30.09 14:49:32 [Server] INFO at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
30.09 14:49:32 [Server] INFO at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
30.09 14:49:32 [Server] INFO at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
30.09 14:49:32 [Server] INFO at me.gnat008.perworldinventory.data.FileWriter$$Lambda$12/222899850.run(Unknown Source)
30.09 14:49:32 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
30.09 14:49:32 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
30.09 14:49:32 [Server] INFO ... 3 more
`
The second is a little more obveous and happens almost every time a player changed worlds or joins the server. It also send that "Something went horrably wrong when loading your inventory!"
`30.09 14:57:37 [Server] ERROR Unable to find inventory data for player 'PAINmatrix' for group 'Minigames': plugins/PerWorldInventory/datadefaults/__default.json (No such file or directory)`

Plugin Version: 1.8.2
Spigot Version: 1.10
Config.yml: http://pastebin.com/5gB5bk7V
Worlds.yml: http://pastebin.com/9DG5W3Q0

**Comment by Gnat008** [comment]
The second error should be fixed with 9d8b643. I guess with the stuff related to moving, it never got released. The first one is still being looked into, but if you could help me by verifying that at least the second error is now gone, that would be wonderful!

**Comment by PAINmatrix** [comment]
The second one is definitely gone, but I am still having troubles with inventories transferring into worlds they should not be. As of the second one I have not seen it recently, so it may also be gone.

**Comment by PAINmatrix** [comment]
```
[17:14:19] [Craft Scheduler Thread - 67/WARN]: Exception in thread "Craft Scheduler Thread - 67" 
[17:14:19] [Craft Scheduler Thread - 67/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 9029
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
	at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
	at me.gnat008.perworldinventory.data.FileWriter$$Lambda$12/958130701.run(Unknown Source)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```
Something similar happened again 3 times, if any help, 2 happened exactly after the a player changed their gamemode and the last one happened after after the worlds saved. All of them were under 2 minutes after.

**Comment by Gnat008** [comment]
Okay, I'm going to close this one, to keep everything focused on Issue #115. Please see and use that one for the NullPointerException error.
