### ISSUE TITLE
got some errors

### ISSUE THREAD

**Issue by Toodo** [Gnat008/PerWorldInventory#134]
hi!
i got some errors
what is it?
i use spigot-1.10.2

`[01:19:15] [Craft Scheduler Thread - 58/WARN]: Exception in thread "Craft Scheduler Thread - 58"
[01:19:15] [Craft Scheduler Thread - 58/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.3 generated an exception while executing task 2089
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:230)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:88)
    at me.gnat008.perworldinventory.data.FileWriter.lambda$saveToDatabase$0(FileWriter.java:80)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more`

**Comment by Gnat008** [comment]
Hello, could you please take a look at Issue #115, sort of the master issue for this error? In the comments there is a link to a special version which adds a debug message to hopefully track down this error. If you could use that, enable debugging in the PWI config, and post a server log in that issue, that would be wonderful!

**Comment by Gnat008** [comment]
See the last comment in #115, if you please. :)

**Comment by Toodo** [comment]
i think that fix the porblem havent seen that issue yet thx :D g8 plugin :)

**Comment by Toodo** [comment]
get some more errors have 1.8.4

`[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player 'Toodo' changed to gamemode 'CREATIVE' in group 'Event'
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Adding player 'Toodo' to cache; key is 'cbf06d3c-24ac-4f3d-abfb-964c30d1a806.Event.survival'
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player 'Toodo' found in cache! Updating cache
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Updating player 'Toodo' in the cache
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Bypass system is disabled in the config, loading data
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Trying to get data from cache for player 'Toodo'
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Looking for cached data with key 'cbf06d3c-24ac-4f3d-abfb-964c30d1a806.Event.creative'
[17:30:57] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player 'Toodo' found in cache! Setting their data
[17:32:51] [Server thread/WARN]: [PerWorldInventory] Task #173 for PerWorldInventory v1.8.4 generated an exception
java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:334) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-047f737-ae93d4f]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

**Comment by Toodo** [comment]
@Gnat008 ^
do you have any idea how to fix the errors :)

**Comment by sloanr333** [comment]
Main Thread for this issue is here: #115 You can find a new download at the bottom, and I believe he would like you to use that and report back with the server logs if the problem keeps happening. :)

**Comment by Toodo** [comment]
@sloanr333 
ok thx :)
