### ISSUE TITLE
Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.8.3

### ISSUE THREAD

**Issue by rustyshakelford2** [Gnat008/PerWorldInventory#139]
The following floods my console from time to time. 

`Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.8.3
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:768) [spigot.jar:git-Spigot-16c940b-0805f60]
	at dk.lockfuglsang.wolfencraft.intercept.PacketInterceptor.createDummyPlayer(PacketInterceptor.java:97) [HolographicScoreboard.jar:?]
	at dk.lockfuglsang.wolfencraft.config.Scoreboard.createBufferedSender(Scoreboard.java:173) [HolographicScoreboard.jar:?]
	at dk.lockfuglsang.wolfencraft.config.Scoreboard.refreshView(Scoreboard.java:132) [HolographicScoreboard.jar:?]
	at dk.lockfuglsang.wolfencraft.HolographicScoreboard$2.run(HolographicScoreboard.java:118) [HolographicScoreboard.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-16c940b-0805f60]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-16c940b-0805f60]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-16c940b-0805f60]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:87) ~[?:?]
	at me.gnat008.perworldinventory.process.GameModeChangeProcess.processGameModeChange(GameModeChangeProcess.java:46) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerGameModeChangeListener.onPlayerGameModeChange(PlayerGameModeChangeListener.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-16c940b-0805f60]
	... 15 more`
[config.yml.txt](https://github.com/Gnat008/PerWorldInventory/files/601781/config.yml.txt)

**Comment by ljacqu** [comment]
> dk.lockfuglsang.wolfencraft.intercept.PacketInterceptor.createDummyPlayer

Do you have a plugin that creates fake players (NPC's)?

**Comment by rustyshakelford2** [comment]
I believe Holographic-Scoreboard does this. I will try disabling it. The fake players do not play nicely with this plugin I assume?

**Comment by Gnat008** [comment]
Hm. I wonder if there is a good way to check if a player is actually a Player...
