### ISSUE TITLE
Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v1.9.0

### ISSUE THREAD

**Issue by Jocke155** [Gnat008/PerWorldInventory#145]
`[01:35:29 ERROR]: Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v1.9.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:117) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_11_R1.EntityPlayer.a(EntityPlayer.java:942) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at net.minecraft.server.v1_11_R1.EntityLiving.addEffect(EntityLiving.java:680) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:300) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:290) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.addPotionEffects(CraftLivingEntity.java:307) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        at me.gnat008.perworldinventory.data.serializers.PotionEffectSerializer.addPotionEffects(PotionEffectSerializer.java:144) ~[?:?]
        at me.gnat008.perworldinventory.data.serializers.PotionEffectSerializer.setPotionEffects(PotionEffectSerializer.java:173) ~[?:?]
        at me.gnat008.perworldinventory.data.serializers.StatSerializer.deserialize(StatSerializer.java:120) ~[?:?]
        at me.gnat008.perworldinventory.data.serializers.PlayerSerializer.deserialize(PlayerSerializer.java:92) ~[?:?]
        at me.gnat008.perworldinventory.data.FileWriter.getFromDatabase(FileWriter.java:127) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:160) ~[?:?]
        at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChange(InventoryChangeProcess.java:117) ~[?:?]
        at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChangeOnSpawn(InventoryChangeProcess.java:70) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerSpawnLocationListener.onPlayerSpawn(PlayerSpawnLocationListener.java:70) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-f950f8e-b64d852]
        ... 13 more`

**Comment by Gnat008** [comment]
Do you know what potion effect this could be? Looks like it could potentially be a bug in Spigot, which I've seen before.

**Comment by CloudeLecaw** [comment]
hmm mine is not so ling but its also a PlayerSpawnLocationEvent... i got it after login a few secounds later 🥉 
[11:37:51] [Server thread/ERROR]: Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v1.9.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:117) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:108) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChangeOnSpawn(InventoryChangeProcess.java:68) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerSpawnLocationListener.onPlayerSpawn(PlayerSpawnLocationListener.java:70) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
	... 13 more
