### ISSUE TITLE
Could not pass event PlayerQuitEvent

### ISSUE THREAD

**Issue by Jocke155** [Gnat008/PerWorldInventory#154]
Spigot version:
CraftBukkit version git-Spigot-7d78b81-7c743ff (MC: 1.11.2)

[19:02:24 ERROR]: Could not pass event PlayerQuitEvent to PerWorldInventory v1.9.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1054) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:192) ~[?:?]
        at me.gnat008.perworldinventory.process.PlayerQuitProcess.processPlayerLeave(PlayerQuitProcess.java:46) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerQuitListener.onPlayerQuit(PlayerQuitListener.java:42) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor743.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        ... 12 more

**Comment by Gnat008** [comment]
@Jocke155 Do you happen to have your worlds.yml file for this?
