### ISSUE TITLE
Task #49 for PerWorldInventory v1.9.0 generated an exception

### ISSUE THREAD

**Issue by Jocke155** [Gnat008/PerWorldInventory#155]
Spigot version:
CraftBukkit version git-Spigot-7d78b81-7c743ff (MC: 1.11.2)

[19:39:16 WARN]: [PerWorldInventory] Task #49 for PerWorldInventory v1.9.0 generated an exception
java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$0(PWIPlayerManager.java:333) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-7c743ff]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Gnat008** [comment]
Please post the contents of your worlds.yml file in issue #147.
