### ISSUE TITLE
Start up InvalidPluginException

### ISSUE THREAD

**Issue by x00dis** [Gnat008/PerWorldInventory#169]
I get the following error when starting up the server

[06:26:36 ERROR]: Could not load 'plugins/perworldinventory-1.9.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/gnat008/perworldinventory/PerWorldInventory : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.UnsupportedClassVersionError: me/gnat008/perworldinventory/PerWorldInventory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_121]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_121]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_121]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_121]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_121]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	... 6 more

**Comment by steve4744** [comment]
Try updating java  - you seem to be running Java 1.7. PWI needs java 1.8.

**Comment by Gnat008** [comment]
@steve4744 is correct. You need to have Java version 1.8 installed.
