### ISSUE TITLE
IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by mibby** [Gnat008/PerWorldInventory#177]
PerWorldInventory v1.9.1 (Spigot page release version.)
Paper dev 1045 (Spigot 1.11.2)

Shut down my server to restart it while a player was in a world with a separate inventory.

```
[02:28:03] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.1
[02:28:03] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.9.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:410) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:129) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:112) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:95) ~[patched_1.11.2.jar:git-Paper-1045]
	at me.gnat008.perworldinventory.BukkitService.runTaskOptionallyAsync(BukkitService.java:60) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:85) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:212) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:86) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:176) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [patched_1.11.2.jar:git-Paper-1045]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:347) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:481) [patched_1.11.2.jar:git-Paper-1045]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:688) [patched_1.11.2.jar:git-Paper-1045]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by xtomyserrax** [comment]
I am getting the same error while reloading or stoping the server!
http://pastebin.com/F4B7Fj0R
I am using spigot 1.11

**Comment by Gnat008** [comment]
@mibby @xtomyserrax Could you guys see my comment on #183 and chime in there? Thanks!

**Comment by mibby** [comment]
Closing since fixed.
