### ISSUE TITLE
As soon as I join the server it shows error Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.5.1

### ISSUE THREAD

**Issue by gotwarzone** [Gnat008/PerWorldInventory#18]
[14:52:00] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.5.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:623) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:476) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:223) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at fr.xephi.authme.listener.AuthMePlayerListener.onPlayerJoin(AuthMePlayerListener.java:668) [AuthMe-3.5-SNAPSHOT.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: World 'SURVIVAL' not found! Could not get group!
	at me.gnat008.perworldinventory.data.WorldManager.getGroupFromWorld(WorldManager.java:73) ~[?:?]
	at me.gnat008.perworldinventory.listeners.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:45) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-d2856ae-8f0f4ed]
	... 26 more
[14:52:00]

**Comment by Gnat008** [comment]
That says that the world 'SURVIVAL' is not found in your worlds.yml  file. Note that this file is case-sensitive.

**Comment by Gnat008** [comment]
Since I haven't heard back, I'll close this out. If the issue is not resolved, please re-open it.
