### ISSUE TITLE
NPE on shutdown

### ISSUE THREAD

**Issue by SlimeDog** [Gnat008/PerWorldInventory#183]
Spigot 1.11.2 latest, PWI 1.9.1

> [14:21:56] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.1
[14:21:56] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.9.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:92) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at me.gnat008.perworldinventory.BukkitService.runTaskOptionallyAsync(BukkitService.java:60) ~[?:?]
        at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:85) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:212) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:86) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:176) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2.jar-2017-02-15-1243:git-Spigot-65a0347-1a71021]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

Nothing further to end of log.

**Comment by Sikatsu** [comment]
Same, I also have this error.

**Comment by Gnat008** [comment]
@SlimeDog @Sikatsu Are either of you able to build the plugin from source? If so, could you see on a test server if the latest build fixes this?

**Comment by Sikatsu** [comment]
I don't have the knowledge for that unfortunatly.

**Comment by Gnat008** [comment]
Here it is then: https://drive.google.com/open?id=0B7hS84xeTkpsQmpBMTdlcEc3ZE0

**Comment by mibby** [comment]
I manually compiled the latest source as of this commit https://github.com/Gnat008/PerWorldInventory/commit/52b9883257921a8c9156b3d603da4eb2c6828159. I will let you know if the error on shutdown still occurs when players are in separate inventory worlds in the next day or so.

**Comment by SlimeDog** [comment]
I grabbed the google drop. The error does not always occur, so it will take a few days to statistically claim that it doesn't happen at all. :)

Also, on startup ...
Spigot 1.11.2 latest, PWI 1.9.2 pre

> [01:44:49] [Server thread/WARN]: [PerWorldInventory] Could not save default.json to plugins/PerWorldInventory/default.json because default.json already exists.

**Comment by SlimeDog** [comment]
I have performed a lot of restarts in the last few hours, testing various plugin updates. I have not seen the NPE-on-shutdown bug behavior, so I think you squashed it.

**Comment by Sikatsu** [comment]
@Gnat008 

20.02 00:24:42 [Server] INFO [PerWorldInventory] Enabling PerWorldInventory v1.9.2
20.02 00:24:42 [Server] WARN [PerWorldInventory] Could not save default.json to plugins/PerWorldInventory/default.json because default.json already exists.
20.02 00:24:42 [Server] INFO [PerWorldInventory] Registering listeners...
20.02 00:24:42 [Server] INFO [PerWorldInventory] Listeners registered!
20.02 00:24:42 [Server] INFO [PerWorldInventory] Registering commands...
20.02 00:24:42 [Server] INFO [PerWorldInventory] Commands registered!
20.02 00:24:42 [Server] INFO [PerWorldInventory] Vault found! Hooking into it...
20.02 00:24:42 [Server] INFO [PerWorldInventory] Hooked into Vault!

**Comment by Gnat008** [comment]
Noted. That doesn't effect anything.

**Comment by mibby** [comment]
I can confirm no more exception on shutdown for me thus far. So you seem to have killed it. :)
