### ISSUE TITLE
NoClassDefFoundError: ch/jalu/injector/InjectorBuilder

### ISSUE THREAD

**Issue by mibby** [Gnat008/PerWorldInventory#187]
Tried compiling the latest source from pom. It compiled successfully but fails to load. 

```
[10:23:43] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.9.2
[10:23:43] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.9.2 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/jalu/injector/InjectorBuilder
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:115) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1055]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: ch.jalu.injector.InjectorBuilder
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1055]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 12 more
[10:23:43] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.2
[10:23:43] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.9.2 (Is it up to date?)
java.lang.NullPointerException
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:194) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1055]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1055]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603) [patched_1.11.2.jar:git-Paper-1055]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by mibby** [comment]
Thanks. Loads properly now. I noticed the final compiled size for 1.9.2 is like a 1/4th the size of 1.9.1 release on spigot. Not sure if intended or something isn't being included, but it does seem to load fine.

**Comment by Gnat008** [comment]
Yeah I forgot to include some of the dependencies after messing with Maven shading.

**Comment by mibby** [comment]
Hopefully nothing absolutely necessary. I was going to leave the latest source up on my live environment since it _seems_ to load fine. :P

**Comment by Gnat008** [comment]
I tested it on my test server and it appears to work just fine now.
