### ISSUE TITLE
Error on can-fly: false in config.yml

### ISSUE THREAD

**Issue by Mario359** [Gnat008/PerWorldInventory#192]
When a player goes to another map, sometimes, this error appears
PerWorldInventory 1.9.1
Spigot 1.11.2
config.yml : 
```manage-gamemodes: false
separate-gamemode-inventories: false
share-if-unconfigured: false
metrics:
    enable: true
    send-number-of-groups: true
    send-number-of-worlds: true
player:
    economy: false
    ender-chest: true
    inventory: true
    stats:
        can-fly: false
        display-name: false
        exhaustion: true
        exp: true
        food: true
        flying: true
        gamemode: false
        health: true
        level: true
        potion-effects: true
        saturation: true
        fall-distance: true
        fire-ticks: true
        max-air: true
        remaining-air: true
save-interval: 300
load-data-on-join: false
debug-mode: false
disable-bypass: false

Error :

[PerWorldInventory] Task #503296 for PerWorldInventory v1.9.1 generated an exception
java.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftPlayer.setFlying(CraftPlayer.java:1194) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at me.gnat008.perworldinventory.data.serializers.StatSerializer.deserialize(StatSerializer.java:82) ~[?:?]
	at me.gnat008.perworldinventory.data.serializers.PlayerSerializer.deserialize(PlayerSerializer.java:93) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.lambda$null$2(FileWriter.java:130) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Gnat008** [comment]
Fixed in v1.11.
