### ISSUE TITLE
Error when shutting down

### ISSUE THREAD

**Issue by x0Z3ro0x** [Gnat008/PerWorldInventory#193]
Hello and thank you for taking the time to check out the issue being caused. The error is posted below, please let me know if I am the one causing this error, or if a bug has been found.

`[21:03:51 INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.1
[21:03:51 ERROR]: Error occurred while disabling PerWorldInventory v1.9.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:92) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at me.gnat008.perworldinventory.BukkitService.runTaskOptionallyAsync(BukkitService.java:60) ~[?:?]
        at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:85) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:212) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:86) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:176) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins%20v1.1.0.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]`

**Comment by heckabecca** [comment]
I'm getting this same error..

`[22:52:44] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.1
[22:52:44] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.9.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109) ~[spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:92) ~[spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at me.gnat008.perworldinventory.BukkitService.runTaskOptionallyAsync(BukkitService.java:60) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:85) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:212) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:86) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:176) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:345) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot-1.11.2-20170102a.jar:git-Spigot-d4f98a3-64277ec]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by x0Z3ro0x** [comment]
Unfortunately I think this developer is inactive. I hired a developer on another plugin that was dead, I will talk to them and see if they will work on this one. Its a really great plugin and its a shame the developer doesn't take more incentive in the project. Life is life though.

**Comment by Gnat008** [comment]
I'm still here, just not as much as I used to be. Doing this takes quite a bit of time, and life takes away from that. That said, I am very much interested in continuing this project, and also that PR's are always welcome! Give me a couple mins to take a look at this.

**Comment by Gnat008** [comment]
Ah right, this is fixed in the still unreleased version.

**Comment by x0Z3ro0x** [comment]
Yeah I understand. You say "unreleased version" when might that be released? Also if the project is something you do want to hand off at some point in the future im sure the coder would be more than happy. I don't know if they will do pulls rather than just take what you have rework it and keep the project on spigot. Idk how all that would work.

Thanks for the attention to the project!

**Comment by Gnat008** [comment]
> Yeah I understand. You say "unreleased version" when might that be released?

Hopefully very shortly. I don't think there's anything else needing to be done for this, just hopefully going to get a couple of eyes on my changes first.

**Comment by x0Z3ro0x** [comment]
Alright thank you. Is there any Dev Downloads we can get before hand? Apologies I haven't been in the hosting business in a few years, so I haven't been actively following you. I have no idea if you have Dev releases or not.

I am one of your users that will pay for the plugin as well as use your dev builds to help test bugs. I don't care if a plugin has bugs just as long as the developer is willing to answer Git Tickets.

**Comment by Superdarco** [comment]
Yes, recently I happened to happen, because I do not know if it's something different

[21:08:30] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.9.1
[21:08:30] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.9.1 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:126) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:109) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:92) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at me.gnat008.perworldinventory.BukkitService.runTaskOptionallyAsync(BukkitService.java:60) ~[?:?]
	at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:85) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:212) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:86) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:176) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:342) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:455) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:603) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by Gnat008** [comment]
Update has been released on Spigot.
