### ISSUE TITLE
To soon to convert my Multiverse to PerWorld ?

### ISSUE THREAD

**Issue by comonier** [Gnat008/PerWorldInventory#197]
i have some warns from multiverse inventories but... nothing so bad like that (other tickets)

should i wait before change my database hummm....

`30.03 00:46:09 [Server] INFO yRafa_PvP issued server command: /home fim
30.03 00:46:09 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 36
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.api.DataStrings.parseInventory(DataStrings.java:421)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:20)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.api.share.InventorySerializer.deserialize(InventorySerializer.java:10)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:76)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:87)
30.03 00:46:09 [Server] WARN at com.onarandombox.multiverseinventories.WorldChangeShareHandler.handle(WorldChangeShareHandler.java:103)
30.03 00:46:12 [Multicraft] Skipped 41 lines due to rate limit (10/s)`

**Comment by comonier** [comment]
Gnat008, i am reading other issues from players, a a lot of ppl with problems, on last build.... is to soon to i choise use that plugin? Better wait you solve this bugs before i update? My machine is using Java 8 with last build of spigot git-Spigot-625bc00-d09304e (...) if you tell me its ok i can use that Per World Inventory 1.9.1 i trust you and go to run "/pwi convert multiverse" - But if you tell me to wait you solve this bugs issues "ppl losing money, itens etc..." of course i will wait.

**Comment by comonier** [comment]
31.03 01:41:27 [Server] WARN [PerWorldInventory] Plugin PerWorldInventory v1.9.1 generated an exception while executing task 1872
31.03 01:41:27 [Server] INFO java.lang.NoClassDefFoundError: com/onarandombox/multiverseinventories/api/share/Sharables
31.03 01:41:27 [Server] INFO at me.gnat008.perworldinventory.data.converters.DataConverter.serializeMVIToNewFormat(DataConverter.java:146) ~[?:?]
31.03 01:41:28 [Multicraft] Skipped 5100 lines due to rate limit (10/s)
