### ISSUE TITLE
[v1.10.0] Null Pointer Exception

### ISSUE THREAD

**Issue by gunleader** [Gnat008/PerWorldInventory#199]
The update fixed the problems my players where having when changing between Worldgroups and loosing inventories.
Still this Null Pointer Error is shown in the console when changing Worlds:

`[22:57:52] [Server thread/WARN]: [PerWorldInventory] Task #354 for PerWorldInventory v1.10.0 generated an exception
java.lang.NullPointerException
at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$3(PWIPlayerManager.java:359) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-96235ab-2aa5ac6]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

**Comment by Gnat008** [comment]
@gunleader Can you show me your worlds.yml file?

**Comment by gunleader** [comment]
`# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  Survival:
    worlds:
    - Survival
    - Farm
    - Nether
    default-gamemode: SURVIVAL
  Hub:
    worlds:
    - Hub
    default-gamemode: ADVENTURE
  dev:
    worlds:
    - dev
    default-gamemode: CREATIVE
`

**Comment by Gnat008** [comment]
@gunleader You have some incorrect spacing in your config file, which is probably breaking YAML.
