### ISSUE TITLE
worlds.yml cleaned

### ISSUE THREAD

**Issue by hexosse** [Gnat008/PerWorldInventory#20]
Hi,

each time i reload or restart the server, the file worlds.yml is cleaned ???

here is the error I got when i restart :
<code>
[16:20:26 ERROR]: Error occurred while enabling PerWorldInventory v1.5.3 (Is it up to date?)
java.lang.NullPointerException
        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:84) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:742) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:628) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:404) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-d2856ae-8f0f4ed]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
</code>

and here is worlds.yml :

<code>
groups:
  world:
    worlds:
    - world
    - world_mine
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
  world_pvp1:
    worlds:
    - world_pvp1
    default-gamemode: SURVIVAL
  world_pvp2:
    worlds:
    - world_pvp2
    default-gamemode: SURVIVAL
</code>

**Comment by Gnat008** [comment]
I am unable to reproduce this issue... Can you paste your normal worlds.yml to hastebin.com for me, please?

**Comment by Gnat008** [comment]
Fixed: https://github.com/Gnat008/PerWorldInventory/commit/ff33cda7e3153027035193c059a5e0c185524b0a

**Comment by hexosse** [comment]
Thanks for the fix.

It now works with 1.5.4
