### ISSUE TITLE
Inventory wipe and plugin throwing out errors

### ISSUE THREAD

**Issue by Capsam500** [Gnat008/PerWorldInventory#203]
**The plugin seems to be having issues when interacting with essentials and simply isn't working on my server. I attach the server log:** 

```
13.04 16:47:12 [Server] ERROR Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.10.0
13.04 16:47:12 [Server] INFO org.bukkit.event.EventException
13.04 16:47:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:66) [EssentialsX-2.0.1.jar:?]
13.04 16:47:12 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
13.04 16:47:12 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
13.04 16:47:12 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
13.04 16:47:12 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
13.04 16:47:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
13.04 16:47:12 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
13.04 16:47:12 [Server] INFO at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
13.04 16:47:19 [Multicraft] Skipped 9 lines due to rate limit (30/s)
13.04 16:47:19 [Server] INFO Capsam500 issued server command: /mv tp creative2
13.04 16:47:19 [Server] ERROR Could not pass event PlayerTeleportEvent to PerWorldInventory v1.10.0
13.04 16:47:19 [Server] INFO org.bukkit.event.EventException
13.04 16:47:19 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:898) [Multiverse-Core-2.5.jar:?]
13.04 16:47:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
13.04 16:47:19 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Multicraft] Skipped 57 lines due to rate limit (30/s)
13.04 16:47:29 [Server] INFO Capsam500 issued server command: /warp castle
13.04 16:47:29 [Server] ERROR Could not pass event PlayerTeleportEvent to PerWorldInventory v1.10.0
13.04 16:47:29 [Server] INFO org.bukkit.event.EventException
13.04 16:47:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.Teleport.now(Teleport.java:139) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.Teleport.warp(Teleport.java:255) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:111) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:46) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
13.04 16:47:29 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
13.04 16:47:29 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
13.04 16:47:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
```

**Comment by BeatlesDev** [comment]
Hi there!

I have determined that you are receiving this error because your server version is 1.8.8 (which didn't have attributes yet which is why you got the error). We have now developed a fix for this since we still want the plugin to be accessible for the 1.8 version of Minecraft, so go ahead and download the new version of PerWorldInventory!

Thank you!
