### ISSUE TITLE
An error occurred copying files?!

### ISSUE THREAD

**Issue by ItsMennyo** [Gnat008/PerWorldInventory#204]
I constantly get this error and therefore sometimes people get lose their inventory!

`This server is running CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)` `PWI version 1.10.0`

`[21:03:46 ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'SkyBlock.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (Het systeem kan het opgegeven bestand niet vinden)
[21:03:46 WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (Het systeem kan het opgegeven bestand niet vinden)
[21:03:46 WARN]:        at java.io.FileInputStream.open0(Native Method)
[21:03:46 WARN]:        at java.io.FileInputStream.open(Unknown Source)
[21:03:46 WARN]:        at java.io.FileInputStream.<init>(Unknown Source)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[21:03:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[21:03:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[21:03:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:03:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[21:03:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[21:03:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:03:46 ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'KitPvP.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (Het systeem kan het opgegeven bestand niet vinden)
[21:03:46 WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (Het systeem kan het opgegeven bestand niet vinden)
[21:03:46 WARN]:        at java.io.FileInputStream.open0(Native Method)
[21:03:46 WARN]:        at java.io.FileInputStream.open(Unknown Source)
[21:03:46 WARN]:        at java.io.FileInputStream.<init>(Unknown Source)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[21:03:46 WARN]:        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[21:03:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[21:03:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[21:03:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:03:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[21:03:46 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
[21:03:46 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[21:03:46 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by Superdarco150** [comment]
Yea, me too

[13:44:32] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.10.0
[13:44:32] [Server thread/WARN]: [PerWorldInventory] Could not save default.json to plugins\PerWorldInventory\default.json because default.json already exists.
[13:44:32] [Server thread/INFO]: [PerWorldInventory] Registering listeners...
[13:44:32] [Server thread/INFO]: [PerWorldInventory] Listeners registered!
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'ASkyBlock.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'juegos.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Candy.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Colores.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Double.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Village.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:44:32] [Server thread/ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'Safari.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[13:44:32] [Server thread/WARN]: 	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[13:44:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[13:44:32] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[13:44:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)


And sometimes this error comes out

[14:05:08] [Craft Scheduler Thread - 68/ERROR]: [PerWorldInventory] Unable to find inventory data for player 'mariano' for group 'juegos': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (El sistema no puede encontrar el archivo especificado)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.io.FileReader.<init>(Unknown Source)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at me.gnat008.perworldinventory.data.FlatFile.getFromDefaults(FlatFile.java:165)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at me.gnat008.perworldinventory.data.FlatFile.lambda$getFromDatabase$2(FlatFile.java:124)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:05:08] [Craft Scheduler Thread - 68/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Gnat008** [comment]
@ItsMennyo @Superdarco150 Could you both try this version [here](https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms) to make sure this is resolved?

**Comment by ItsMennyo** [comment]
It totally works again! Now the plugin says only this: "`[PerWorldInventory] Could not save default.json to plugins\PerWorldInventory\default.json because default.json already exists.`" but it's better than long error that sometimes lets you remove inventory 😋

**Comment by Gnat008** [comment]
I'll create a new issue for that one and close this one, then.
