### ISSUE TITLE
Loading inventory error

### ISSUE THREAD

**Issue by ghost** [Gnat008/PerWorldInventory#206]
Whenever a player joins the server or goes to a world for the first time it says there was an error or something loading the inventory. Is there a way to stop this from happening? (I'm assuming it's because if they are new it means they have nothing to load when joining)

**Comment by ItsMennyo** [comment]
Whats the error?

**Comment by Gnat008** [comment]
@ChickenPillow Can you try [this](https://drive.google.com/open?id=0B7hS84xeTkpsSzRUS1FkekFGbms) version and see if it still happens?

**Comment by ChickenPillow** [comment]
Still getting the error

**Comment by Gnat008** [comment]
Could you please post the full error text?

**Comment by ChickenPillow** [comment]
In Game it says:

>> Something went horribly wrong when loading your inventory!
Please notify a server administrator!

And on the console it says this:

[18:19:38] [Craft Scheduler Thread - 20/ERROR]: [PerWorldInventory] Unable to find inventory data for player 'ChickenPillow' for group 'KitPvP': [FileNotFoundException] plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: java.io.FileNotFoundException: plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.io.FileInputStream.open0(Native Method)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.io.FileInputStream.open(FileInputStream.java:195)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.io.FileInputStream.(FileInputStream.java:138)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.io.FileReader.(FileReader.java:72)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at me.gnat008.perworldinventory.data.FlatFile.getFromDefaults(FlatFile.java:165)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at me.gnat008.perworldinventory.data.FlatFile.lambda$getFromDatabase$2(FlatFile.java:124)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:19:38] [Craft Scheduler Thread - 20/WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by ChickenPillow** [comment]
Just checking whether you saw this?

**Comment by ChickenPillow** [comment]
Just checking whether you saw this?

**Comment by Gnat008** [comment]
Fixed in v1.11.
