### ISSUE TITLE
An error when the server goes out...

### ISSUE THREAD

**Issue by ItsMennyo** [Gnat008/PerWorldInventory#210]
I use the version you gave me last where it was rectified the __default.json bug.

`[15:44:15 ERROR]: Could not pass event PlayerKickEvent to PerWorldInventory v1.10.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.disconnect(PlayerConnection.java:226) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:58) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:740) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [Spigot.jar:git-Spigot-c6871e2-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.RuntimeException: Essentials API is called before Essentials is loaded.
        at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:62) ~[?:?]
        at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:85) ~[?:?]
        at com.earth2me.essentials.api.Economy.getMoney(Economy.java:81) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:78) ~[?:?]
        at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.updateCache(PWIPlayerManager.java:405) ~[?:?]
        at me.gnat008.perworldinventory.process.PlayerQuitProcess.processPlayerLeave(PlayerQuitProcess.java:41) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerQuitListener.onPlayerKick(PlayerQuitListener.java:48) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-c6871e2-0cd0397]
        ... 12 more`

**Comment by Gnat008** [comment]
Looks like Essentials is being disabled before PWI can get player balances...

**Comment by ItsMennyo** [comment]
Mmm... that's weird. He was still active but I still get this often. Fortunately, "economy:" is on false so it would not matter much... I think 😋
