### ISSUE TITLE
Plugin ERROR, don't work and have An in-game error

### ISSUE THREAD

**Issue by Aeadnerr** [Gnat008/PerWorldInventory#237]
READ MY PROBLEM! THIS PLUGIN HAVE A BIG PROBLEM!!!!

If I set up my PerWorldInvertory, in the worlds.yml fille.
Everything is good but if i reload the plugin, give this error in the console:

[09:19:57 ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'skyblock.json': [FileNotFoundException] plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
[09:19:57 WARN]: java.io.FileNotFoundException: plugins/PerWorldInventory/data/defaults/__default.json (No such file or directory)
[09:19:57 WARN]: at java.io.FileInputStream.open0(Native Method)
[09:19:57 WARN]: at java.io.FileInputStream.open(FileInputStream.java:195)
[09:19:57 WARN]: at java.io.FileInputStream.<init>(FileInputStream.java:138)
[09:19:57 WARN]: at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[09:19:57 WARN]: at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[09:19:57 WARN]: at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[09:19:57 WARN]: at me.gnat008.perworldinventory.commands.ReloadCommand.executeCommand(ReloadCommand.java:28)
[09:19:57 WARN]: at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295)
[09:19:57 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:19:57 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:19:57 WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:19:57 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:19:57 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[09:19:57 WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[09:19:57 WARN]: at java.lang.Thread.run(Thread.java:745)

My server version: 1.11.2
My worlds.yml:
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
# default:
# worlds:
# - world
# - world_nether
# - world_the_end
# default-gamemode: SURVIVAL
# creative:
# worlds:
# - creative
# default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
default:
worlds:
- world
- world_nether
- world_the_end
default-gamemode: SURVIVAL
skyblock:
worlds:
- skyblock
default-gamemode: CREATIVE

**Comment by ljacqu** [comment]
Can you reformat your post so it makes sense? Put blocks of YAML inside <code>```</code>. 

https://guides.github.com/features/mastering-markdown/

**Comment by Gnat008** [comment]
Fixed in v1.11.
