### ISSUE TITLE
Inventories disappear when switching worlds, don't come back

### ISSUE THREAD

**Issue by JdeFalconr** [Gnat008/PerWorldInventory#249]
Running Spigot 1.12.1, PWI 1.10.1 (latest I could find on the site). Config file, Worlds file and latest server log from reproducing the problem is also attached.
[Logs.zip](https://github.com/Gnat008/PerWorldInventory/files/1243945/Logs.zip)

Pretty much as the title describes. For myself and all our players inventories clear out when moving between worlds and do not come back. For some of my players if they die in one world they respawn in a different world. I've got debugging already turned on so I've attached the latest logfile from the server. 

Please let me know what additional info you'd like and thanks in advance for the help.

**Comment by JdeFalconr** [comment]
More information: Looks like there are now errors showing in the logs. I've attached the latest. Some examples:

> [11:46:46] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Saving logout data for player 

> 'JdeFalconr'...
> [11:46:46] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to PerWorldInventory v1.10.1
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:399) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1096) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:321) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
> Caused by: java.lang.NullPointerException
> 	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:199) ~[?:?]
> 	at me.gnat008.perworldinventory.process.PlayerQuitProcess.processPlayerLeave(PlayerQuitProcess.java:46) ~[?:?]
> 	at me.gnat008.perworldinventory.listeners.player.PlayerQuitListener.onPlayerQuit(PlayerQuitListener.java:42) ~[?:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	... 12 more
> [11:46:46] [Server thread/INFO]: JdeFalconr left the game
[latest.log.txt](https://github.com/Gnat008/PerWorldInventory/files/1254638/latest.log.txt)


Also lots and lots of these:

> [05:25:32] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player: JdeFalconr
> [05:25:32] [Server thread/WARN]: [PerWorldInventory] Task #4 for PerWorldInventory v1.10.1 generated an exception
> java.lang.NullPointerException: null
> 	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$3(PWIPlayerManager.java:359) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.9.jar:git-Spigot-65e8124-357b573]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
> [05:30:33] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Saving cached player with key '2ae8eebd-559c-4cc3-80d1-414a473f8e99.World_7_Nether.survival'
>

**Comment by ElementalShadow** [comment]
Same happened to me

**Comment by FatmanC** [comment]
nice to see issues are getting commented on :/ Im getting same issues too1.12
