### ISSUE TITLE
Cannot make player fly if getAllowFlight() is false

### ISSUE THREAD

**Issue by Oruss7** [Gnat008/PerWorldInventory#252]
```
[09:32:43] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.10.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:713) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:539) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at com.earth2me.essentials.Teleport.now(Teleport.java:139) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Teleport.teleport(Teleport.java:198) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Teleport.warp(Teleport.java:255) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:112) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:47) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1386) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1221) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Cannot make player fly if getAllowFlight() is false
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setFlying(CraftPlayer.java:1194) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getDataFromCache(PWIPlayerManager.java:264) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:167) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChange(InventoryChangeProcess.java:117) ~[?:?]
	at me.gnat008.perworldinventory.process.InventoryChangeProcess.preProcessWorldChange(InventoryChangeProcess.java:54) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:39) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
	... 29 more
```

**Comment by Gnat008** [comment]
Fixed by 78e8050
