### ISSUE TITLE
An error occurred copying file '__default.json'

### ISSUE THREAD

**Issue by Jocke155** [Gnat008/PerWorldInventory#256]
`[23:04:21 ERROR]: [PerWorldInventory] An error occurred copying file '__default.json' to 'creative.json': [FileNotFoundException] plugins\PerWorldInventory\data\defaults\__default.json (Det gÕr inte att hitta filen)
[23:04:21 WARN]: java.io.FileNotFoundException: plugins\PerWorldInventory\data\defaults\__default.json (Det gÕr inte att hitta filen)
[23:04:21 WARN]:        at java.io.FileInputStream.open0(Native Method)
[23:04:21 WARN]:        at java.io.FileInputStream.open(Unknown Source)
[23:04:21 WARN]:        at java.io.FileInputStream.<init>(Unknown Source)
[23:04:21 WARN]:        at me.gnat008.perworldinventory.util.FileUtils.copyFile(FileUtils.java:23)
[23:04:21 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.setDefaultsFile(GroupManager.java:187)
[23:04:21 WARN]:        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:155)
[23:04:21 WARN]:        at me.gnat008.perworldinventory.commands.ReloadCommand.executeCommand(ReloadCommand.java:28)
[23:04:21 WARN]:        at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295)
[23:04:21 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:04:21 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:04:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[23:04:21 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[23:04:21 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[23:04:21 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[23:04:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[23:04:21 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[23:04:21 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by Jocke155** [comment]
Solved by renaming the existing:
plugins\PerWorldInventory\data\defaults\default.json
to:
__default.json

Still doesn't separate the world inventories however.

**Comment by Gnat008** [comment]
Fixed in v1.11 version.
