### ISSUE TITLE
Java 9 support.

### ISSUE THREAD

**Issue by mibby** [Gnat008/PerWorldInventory#260]
Java 9
PerWorldInventory v1.10.0
Paper dev 1220 (Spigot 1.12.2)

```
[02:53:17] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.10.0
[02:53:17] [Server thread/WARN]: [PerWorldInventory] Could not save default.json to plugins/PerWorldInventory/default.json because default.json already exists.
[02:53:17] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.10.0 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
	at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[patched_1.12.2.jar:git-Paper-1220]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 20 more
[02:53:17] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.10.0
[02:53:17] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.10.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:191) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1220]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1220]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1220]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by Gnat008** [comment]
Pinging @ljacqu because this also affects dependency injection.

**Comment by ljacqu** [comment]
Thank you for the ping! Relates to https://github.com/ljacqu/DependencyInjector/issues/52, which I forgot about

**Comment by Alvaroctal** [comment]
Same goes here, 

Java 9
PerWorldInventory v1.11.0
Spigot 1.12.1

[13:19:23] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11
[13:19:23] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.11 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
	at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-7754231-a3b3a42]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-7754231-a3b3a42]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 20 more

**Comment by Gnat008** [comment]
Should be compatible with Java 9 in the next release (currently planned as 1.12).

**Comment by The947thTokay** [comment]
```[16:09:31 INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.12-beta.2
[16:09:31 ERROR]: Error occurred while enabling PerWorldInventory v1.12-beta.2 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
        at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
        at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
        at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 20 more```
@Gnat008 still getting this error. I saw that 1.12-beta.1 added Java 9 compitability, but it doesn't seem to have changed things...

**Comment by mibby** [comment]
Can also confirm. 1.12-beta.2 errors on Java 9.0.1.

```
[05:40:33] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.12-beta.2
[05:40:33] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.12-beta.2 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
	at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1248]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1248]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 20 more
[05:40:33] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.12-beta.2
[05:40:33] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.12-beta.2 (Is it up to date?)
java.lang.NullPointerException: null
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:191) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1248]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by Gnat008** [comment]
@ljacqu Any ideas? Maybe I have to shade something else into PWI...

**Comment by The947thTokay** [comment]
@Gnat008 just curious, is there any progress being made?

**Comment by Geant200** [comment]
Hello, I'm having the same problem.

Version.
Spigot 1.12
EpicWorldGenerator v8 PRE-RELEASE-2

`[19:17:18] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.1
[19:17:18] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.11.1 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
	at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [spigot.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-596221b-2c5c611]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-596221b-2c5c611]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-596221b-2c5c611]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-596221b-2c5c611]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 20 more`

an idea ?.

Thank you in advance.

**Comment by ljacqu** [comment]
Woop, this should not be happening with the new dependency...

**Comment by Geant200** [comment]
I did the test again.
I deleted the plugin completely and redo the installation.
Always the same.

**Comment by The947thTokay** [comment]
@ljacqu is the dependency updated already then (in PWI)? Doesn’t look like anything changed...

**Comment by ljacqu** [comment]
![pwi_1 12](https://user-images.githubusercontent.com/8417009/33498735-c35630aa-d6d2-11e7-92fb-fd6519e1e640.png)

**Comment by The947thTokay** [comment]
I’ll try it soon!

**Comment by The947thTokay** [comment]
Now that I've finally built PWI (#280), I thought it would finally work...
No luck. @ljacqu, how did you get that version?
