### ISSUE TITLE
InventoryLoadEvent

### ISSUE THREAD

**Issue by charbeltrad** [Gnat008/PerWorldInventory#268]
Here's My error when someone joins..

[10:35:35 INFO]: UUID of player BlazingOne is XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX (that's not my UUID I just covered it)

[10:35:35 ERROR]: Could not pass event InventoryLoadEvent to PerWorldInventory v1.11.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at me.gnat008.perworldinventory.BukkitService.callEvent(BukkitService.java:91) [perworldinventory-1.11.1.jar:?]
        at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChange(InventoryChangeProcess.java:116) [perworldinventory-1.11.1.jar:?]
        at me.gnat008.perworldinventory.process.InventoryChangeProcess.processWorldChangeOnSpawn(InventoryChangeProcess.java:72) [perworldinventory-1.11.1.jar:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerSpawnLocationListener.onPlayerSpawn(PlayerSpawnLocationListener.java:70) [perworldinventory-1.11.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:123) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_12_R1.EntityPlayer.b(EntityPlayer.java:1107) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.EntityLiving.removeEffect(EntityLiving.java:727) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:329) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:76) ~[?:?]
        at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:55) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:164) ~[?:?]
        at me.gnat008.perworldinventory.listeners.server.InventoryLoadingListener.onInventoryLoad(InventoryLoadingListener.java:49) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        ... 25 more

Also when the server stops...

java.lang.NullPointerException: null
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.savePlayer(PWIPlayerManager.java:199) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.onDisable(PWIPlayerManager.java:90) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:191) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:342) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:464) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:612) [spigot.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

Any Ideas?

**Comment by Gnat008** [comment]
What potion effects did you have active?

**Comment by BlazingOne** [comment]
None..
