### ISSUE TITLE
Could not pass event PlayerDeathEvent to PerWorldInventory v1.11.1

### ISSUE THREAD

**Issue by HappyKilling** [Gnat008/PerWorldInventory#269]
[15:12:24] [Server thread/INFO]: [0;30;1m» [0;36;22mlesangh [0;37;22ma été tué par [0;31;1mFawokQ_Q[m
[15:12:24] [Server thread/INFO]: [0;36;1mFawokQ_Q fait un killstreak de 35 kills![m
[15:12:24] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to PerWorldInventory v1.11.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityPlayer.die(EntityPlayer.java:417) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:812) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:800) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:496) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
	at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 22 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.attribute.Attribute
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
	at me.gnat008.perworldinventory.listeners.player.PlayerDeathListener.onPlayerDeath(PlayerDeathListener.java:53) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 22 more

**Comment by Gnat008** [comment]
What version of Spigot are you running?

**Comment by HappyKilling** [comment]
Spigot 1.8

**Comment by Gnat008** [comment]
1.8, or 1.8.something?

**Comment by HappyKilling** [comment]
1.8.8 R0.1

**Comment by Gnat008** [comment]
Well, that narrows down when Bukkit Attributes were added.

**Comment by HappyKilling** [comment]
you the best :)

**Comment by Music4lity** [comment]
Nothing is working on the PaperSpigot 1.8.8 Snapshot. Player inventories are also being deleted, along with their enderchest contents.

**Comment by Gnat008** [comment]
Could you guys try this pre-release version and see if it's fixed? https://github.com/Gnat008/PerWorldInventory/releases/tag/v1.11.2-beta.1

**Comment by NoopyyGaming** [comment]
It the same, it's not working for me with the v1.11.2

**Comment by Gnat008** [comment]
@NoopyyGaming Are you using CraftBukkit or Spigot?

**Comment by NoopyyGaming** [comment]
Spigot

**Comment by BeatlesDev** [comment]
Hi there!

I have determined that you are receiving this error because your server version is 1.8.8 (which didn't have attributes yet which is why you got the error). We have now developed a fix for this since we still want the plugin to be accessible for the 1.8 version of Minecraft, so go ahead and download the new version of PerWorldInventory!

Thank you!
