### ISSUE TITLE
Plugin won't enable

### ISSUE THREAD

**Issue by The947thTokay** [Gnat008/PerWorldInventory#270]
On my server, the plugin throws an error on startup. It doesn't do anything afterwards.
I get this error at both this version and 1.10.0.
Error:
```[PerWorldInventory] Enabling PerWorldInventory v1.11.2
[12:05:35 ERROR]: Error occurred while enabling PerWorldInventory v1.11.2 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
        at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
        at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
        at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:192) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-7754231-362ed32]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 20 more

**Comment by Gnat008** [comment]
That's due to Java 9 not having an annotation anymore; will be fixed in an upcoming update. See #260.
