### ISSUE TITLE
error per world inventory

### ISSUE THREAD

**Issue by peterjenp** [Gnat008/PerWorldInventory#275]
Hey
on one server I get to see the next error when I load the plugin.
what am I doing wrong because the plugin does not seem to work well either
[code]
[19:12:10] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.1
[19:12:10] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader PerWorldInventory v1.11.1
[19:12:10] [Server thread/INFO]: [PerWorldInventory] Registering listeners...
[19:12:10] [Server thread/INFO]: [PerWorldInventory] Listeners registered!
[19:12:10] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.11.1 (Is it up to date?)
java.lang.NullPointerException: null
        at me.gnat008.perworldinventory.groups.GroupManager.loadGroupsToMemory(GroupManager.java:131) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:125) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-93e20b3$
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPl$
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-93e20b$
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Spigot-93e20b3-$
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Spigot-93e20b3$
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-93e20b3-b8f84$
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-93e20b3-b8f84$
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-93e20b3-b8f84$
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-93e20b3-b8$
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-93e20b3-b8f$
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

[/code]

**Comment by Gnat008** [comment]
Are you using PerWorldPlugins?

**Comment by peterjenp** [comment]
yes I use PerWorldPlugins.
This is because certain plugins may not be available on one server in all worlds.
however, perworld inventory has been indicated to be available in all the world.


________________________________
Van: Gnat008 <notifications@github.com>
Verzonden: Monday, November 27, 2017 9:59:32 PM
Aan: Gnat008/PerWorldInventory
CC: peterjenp; Author
Onderwerp: Re: [Gnat008/PerWorldInventory] error per world inventory (#275)


Are you using PerWorldPlugins?
