### ISSUE TITLE
Error per world inventory

### ISSUE THREAD

**Issue by BetaPlays3** [Gnat008/PerWorldInventory#281]
if i execute the command "is", after "spawn", after "is" generates an error

 Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.8.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:588) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.teleport(CraftPlayer.java:475) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.teleport(CraftEntity.java:223) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1262) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.GridManager.homeTeleport(GridManager.java:1229) [askyblock.jar:?]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1068) [askyblock.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.updateCache(PWIPlayerManager.java:383) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:97) ~[?:?]
        at me.gnat008.perworldinventory.process.InventoryChangeProcess.preProcessWorldChange(InventoryChangeProcess.java:48) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:39) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-550ebac-7019900]
        ... 24 more

**Comment by BeatlesDev** [comment]
Please try to update to the latest version of PWI and see what happens.
