### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OinkyOverlord** [Gnat008/PerWorldInventory#282]
I got the following error when trying to start PWI:
`[12:08:50 ERROR]: Error occurred while enabling PerWorldInventory v1.11.1 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
        at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
        at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
        at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-f46ccd7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 20 more`

**Comment by ljacqu** [comment]
#260
