### ISSUE TITLE
I'm not what sure is going on but this is what the console shows

### ISSUE THREAD

**Issue by lucasvilla97** [Gnat008/PerWorldInventory#285]
[19:24:33 ERROR]: Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at com.walrusone.skywars.game.Game.startGame(Game.java:412) [SkyWarsReloaded.jar:?]
        at com.walrusone.skywars.commands.StartCmd.run(StartCmd.java:26) [SkyWarsReloaded.jar:?]
        at com.walrusone.skywars.commands.BaseCmd.processCmd(BaseCmd.java:43) [SkyWarsReloaded.jar:?]
        at com.walrusone.skywars.commands.CmdManager.onCommand(CmdManager.java:59) [SkyWarsReloaded.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
        at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerGameModeChangeListener.onPlayerGameModeChange(PlayerGameModeChangeListener.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 24 more
[19:24:42 INFO]: Midwat issued server command: /swr
[19:24:45 INFO]: Midwat issued server command: /swr shop
[19:24:56 INFO]: [24]<+Staff [Owner] Daniel> pero aun no está la tienda
[19:25:05 INFO]: Midwat issued server command: /tp chrispcr
[19:25:05 ERROR]: Could not pass event PlayerTeleportEvent to PerWorldInventory v1.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:444) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at com.earth2me.essentials.Teleport.now(Teleport.java:126) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:194) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Teleport.teleport(Teleport.java:151) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:41) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials-2.x-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials-2.x-SNAPSHOT.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
        at me.gnat008.perworldinventory.data.players.PWIPlayer.<init>(PWIPlayer.java:94) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerFactory.create(PWIPlayerFactory.java:37) ~[?:?]
        at me.gnat008.perworldinventory.data.players.PWIPlayerManager.addPlayer(PWIPlayerManager.java:118) ~[?:?]
        at me.gnat008.perworldinventory.listeners.player.PlayerTeleportListener.onPlayerTeleport(PlayerTeleportListener.java:51) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        ... 27 more

**Comment by BeatlesDev** [comment]
Hi there!

I have determined that you are receiving this error because your server version is 1.8.8 (which didn't have attributes yet which is why you got the error). We have now developed a fix for this since we still want the plugin to be accessible for the 1.8 version of Minecraft, so go ahead and download the new version of PerWorldInventory!

Thank you!
