### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JeNNySS** [Gnat008/PerWorldInventory#287]
08:52:46 INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.1
[08:52:46 ERROR]: Error occurred while enabling PerWorldInventory v1.11.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/JsonObject
   at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_101]
   at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_101]
   at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_101]
   at ch.jalu.injector.utils.ReflectionUtils.safeGetDeclaredMethods(ReflectionUtils.java:165) ~[?:?]
   at ch.jalu.injector.handlers.instantiation.StandardInjectionProvider.validateHasNoInjectMethods(StandardInjectionProvider.java:156) ~[?:?]
   at ch.jalu.injector.handlers.instantiation.StandardInjectionProvider.validateInjection(StandardInjectionProvider.java:142) ~[?:?]
   at ch.jalu.injector.handlers.instantiation.DefaultInjectionProvider.validateInjection(DefaultInjectionProvider.java:24) ~[?:?]
   at ch.jalu.injector.handlers.instantiation.StandardInjectionProvider.safeGet(StandardInjectionProvider.java:43) ~[?:?]
   at ch.jalu.injector.handlers.instantiation.DirectInstantiationProvider.get(DirectInstantiationProvider.java:18) ~[?:?]
   at ch.jalu.injector.InjectorImpl.getInstantiation(InjectorImpl.java:217) ~[?:?]
   at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:172) ~[?:?]
   at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
   at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
   at me.gnat008.perworldinventory.data.DataSourceProvider.createDataSource(DataSourceProvider.java:35) ~[?:?]
   at me.gnat008.perworldinventory.data.DataSourceProvider.get(DataSourceProvider.java:22) ~[?:?]
   at me.gnat008.perworldinventory.data.DataSourceProvider.get(DataSourceProvider.java:12) ~[?:?]
   at ch.jalu.injector.handlers.provider.ProviderHandlerImpl$UninitializedProviderInstantiation.instantiateWith(ProviderHandlerImpl.java:141) ~[?:?]
   at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:181) ~[?:?]
   at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
   at ch.jalu.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:208) ~[?:?]
   at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:177) ~[?:?]
   at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
   at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
   at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:199) ~[?:?]
   at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:119) ~[?:?]
   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:746) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.Bukkit.reload(Bukkit.java:534) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [server.jar:git-Spigot-c3c767f-33d5de3]
   at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [server.jar:git-Spigot-c3c767f-33d5de3]
   at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [server.jar:git-Spigot-c3c767f-33d5de3]
   at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [server.jar:git-Spigot-c3c767f-33d5de3]
   at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Spigot-c3c767f-33d5de3]
   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonObject
   at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-c3c767f-33d5de3]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-c3c767f-33d5de3]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
   ... 41 more

**Comment by Gnat008** [comment]
What version of Spigot are you running?

**Comment by JeNNySS** [comment]
Spigot 1.8

**Comment by Gnat008** [comment]
That would be why. In one of the 1.8.x sub-versions, Spigot moved the Gson package.

**Comment by JeNNySS** [comment]
Where I can download? Please LINK

**Comment by JeNNySS** [comment]
HEYYYYY

**Comment by JeNNySS** [comment]
HEEEY

**Comment by MrEminent42** [comment]
Hey, I'm also having this problem. Would it be possible to link to a download for 1.8.8?

**Comment by MrEminent42** [comment]
@The947thTokay Sorry I meant PWI. I found a version for 1.8.8 on BukkitDev. @JeNNySS I recommend downgrading to [version 1.5.8](https://dev.bukkit.org/projects/world-inventory/files/892715) if you're using 1.8.8.

**Comment by The947thTokay** [comment]
Oops...

**Comment by BeatlesDev** [comment]
I have checked your Minecraft version and I have determined that it is pre-1.8.3...definitely too old for PWI! I recommend upgrading to at least 1.8.8 (which is PWI compatible)!
