### ISSUE TITLE
Bug - No aparently trigger

### ISSUE THREAD

**Issue by itaquito** [Gnat008/PerWorldInventory#288]
Hey! I got this error it trigger randomly, it doesnt have a pattern

[PerWorldInventory] Task #47 for PerWorldInventory v1.11.1 generated an exception
java.lang.NullPointerException: null
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$3(PWIPlayerManager.java:377) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[22:15:35] [Async Chat Thread - #9/INFO]: [0;31;1m[Creador] [m [0;31;22m[21mRECstone27[m[m [0;37;22m>>[0;37;1m es lo que dije :I[m

**Comment by itaquito** [comment]
it started when I put this into the worlds.yml

  skyblock:
    worlds:
    - ASkyBlock
    - ASkyBlock_nether
    - SkyblockLobby
    default-gamemode: SURVIVAL

Thats for the skyblock gamemode

**Comment by Gnat008** [comment]
Can you put your worlds config inside code tags? I need to see the formatting (spaces). I suspect one of them is off.

**Comment by itaquito** [comment]
in pastebin?

**Comment by Gnat008** [comment]
You could do that. That'll work.

**Comment by itaquito** [comment]
https://pastebin.com/fdLPbx5p

**Comment by Gnat008** [comment]
Hm that looks correct... Can you enable debugging in the main config and do `/pwi reload`? It will output the loaded groups to the console/log. I want to see what it loads for groups.

**Comment by itaquito** [comment]
Sure!

Give me a sec

**Comment by itaquito** [comment]
[22:40:46] [Server thread/INFO]: _itaquito_ issued server command: /pwi reload
[22:40:46] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Adding group to memory. Group: default Worlds: [world, world_nether, world_the_end] Gamemode: SURVIVAL
[22:40:46] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Adding group to memory. Group: skyblock Worlds: [ASkyBlock, ASkyBlock_nether, SkyblockLobby] Gamemode: SURVIVAL

**Comment by itaquito** [comment]
This is what happens just after the error triggers:

[22:40:11] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Adding group to memory. Group: default Worlds: [world, world_nether, world_the_end] Gamemode: SURVIVAL
[22:40:11] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Adding group to memory. Group: skyblock Worlds: [ASkyBlock, ASkyBlock_nether, SkyblockLobby] Gamemode: SURVIVAL
[22:40:18] [Async Chat Thread - #18/INFO]: [0;35;1m[Developer] [m_itaquito_[m[m [0;37;22m>>[0;37;1m espera[m
[22:40:22] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Saving cached player with key 'fe529210-5d82-4dbb-8cc9-422c83a4f876.SkyblockLobby.survival'
[22:40:22] [Server thread/INFO]: [PerWorldInventory] [DEBUG] Player: _itaquito_
[22:40:22] [Server thread/WARN]: [PerWorldInventory] Task #47 for PerWorldInventory v1.11.1 generated an exception
java.lang.NullPointerException: null
	at me.gnat008.perworldinventory.data.players.PWIPlayerManager.lambda$scheduleRepeatingTask$3(PWIPlayerManager.java:377) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[22:40:44] [Async Chat Thread - #18/INFO]: [0;35;1m[Developer] [m_itaquito_[m[m [0;37;22m>>[0;37;1m ----[m

**Comment by Gnat008** [comment]
O.o It's using the incorrect key... Why is it doing that...

**Comment by Gnat008** [comment]
I suppose that if there were already players cached for that world before the plugin was reloaded, this would happen...

**Comment by itaquito** [comment]
So, How i can solve it?

**Comment by Gnat008** [comment]
Short term, restart the server and it should be fine. Out of curiosity, is this a brand new world, or have your players been using it before you added it to the config?

**Comment by Gnat008** [comment]
Copied from the other project issue:
"i just stopped the server and then reopened it and it solved the problem...
Thanks! I love your fast response.... Best dev ever"

Closing this one out, since all new issues will be going to the rewrite.

**Comment by itaquito** [comment]
I dont knowif its ideal to reply but, not alot of players played on the world maybe 2 or 3.

Also suggestion: Perworldspawnpoints :D

**Comment by Gnat008** [comment]
Oh I forgot I had asked that question already. I'm sorry. Not sure how much it matters then, but they'll have lost their inventories for those worlds since they're in a new group.

**Comment by itaquito** [comment]
Hmm, No they hadnt :thinking:
