### ISSUE TITLE
PerWorldInventory is not up to date

### ISSUE THREAD

**Issue by maarcuss** [Gnat008/PerWorldInventory#294]
I have perworldinventory installed on my server, but whenever i start the server it says:

**[Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.1
[Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.11.1 (Is it up to date?)**
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:198) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
... 20 more

i have reinstalled the plugin 2 times and the latest verision on spigotmc.org is 1.11.1 (thats the one i have)

**Comment by Gnat008** [comment]
See #260.
