### ISSUE TITLE
I got an error

### ISSUE THREAD

**Issue by Wolffy821** [Gnat008/PerWorldInventory#296]
Hi , I use '/pwi setworlddefault' and it doesn't work. I go onto the console and it says this : 
`org.bukkit.command.CommandException: Unhandled exception executing command 'pwi' in plugin PerWorldInventory v1.11.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/attribute/Attribute
at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:73) ~[?:?]
at me.gnat008.perworldinventory.data.FlatFile.setGroupDefault(FlatFile.java:251) ~[?:?]
at me.gnat008.perworldinventory.commands.SetWorldDefaultCommand.executeCommand(SetWorldDefaultCommand.java:51) ~[?:?]
at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
... 15 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.attribute.Attribute
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
at me.gnat008.perworldinventory.util.Utils.zeroPlayer(Utils.java:73) ~[?:?]
at me.gnat008.perworldinventory.data.FlatFile.setGroupDefault(FlatFile.java:251) ~[?:?]
at me.gnat008.perworldinventory.commands.SetWorldDefaultCommand.executeCommand(SetWorldDefaultCommand.java:51) ~[?:?]
at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:295) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
... 15 more`
Can anyone help ? Thanks 👍

**Comment by BeatlesDev** [comment]
Hi there!

I have determined that you are receiving this error because your server version is 1.8.8 (which didn't have attributes yet which is why you got the error). We have now developed a fix for this since we still want the plugin to be accessible for the 1.8 version of Minecraft, so go ahead and download the new version of PerWorldInventory!

Thank you!
