### ISSUE TITLE
EROOR WHEN /pwi and inventorys don't change

### ISSUE THREAD

**Issue by CrabGame** [Gnat008/PerWorldInventory#297]
For a while ago ut randomly stoped working. It wont change inventorys. And if you do /pwi it says (Error) please help.

**Comment by CrabGame** [comment]
When i typr /pwi it says:

[21:25:18 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pwi' in plugin PerWorldInventory v1.11.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:277) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]

**Comment by CrabGame** [comment]
Please Help

**Comment by Gnat008** [comment]
Does the command always give that error? What about other commands like `/pwi help` or `/pwi version`?

**Comment by CrabGame** [comment]
/pwi help gives me

ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pwi' in plugin PerWorldInventory v1.11.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:298) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        ... 15 more

**Comment by CrabGame** [comment]
and

**Comment by CrabGame** [comment]
/pwi version give me:


ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pwi' in plugin PerWorldInventory v1.11.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-549c1fa-8c37e2e]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at me.gnat008.perworldinventory.PerWorldInventory.onCommand(PerWorldInventory.java:298) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-549c1fa-8c37e2e]
        ... 15 more

**Comment by Gnat008** [comment]
Are there any errors on server start relating to PWI?

**Comment by CrabGame** [comment]
i will look

**Comment by CrabGame** [comment]
1 sec

**Comment by CrabGame** [comment]
Sir i have a question do i need to eun last update on my spigot server. Because thats no problem if it's so Sir

**Comment by Gnat008** [comment]
From those stacktraces above, you're already running the latest version of PWI.

**Comment by CrabGame** [comment]
yes but i have a 15 sec wait time when i start my server and it says Update your spigot server

**Comment by CrabGame** [comment]
here:

*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/ ***
*** Server will start in 15 seconds ***

**Comment by CrabGame** [comment]
thats maybe why

**Comment by Gnat008** [comment]
Doesn't matter for this issue unless you're running some ancient build of 1.8.0.

**Comment by CrabGame** [comment]
ok well im runing 1.12.2

**Comment by CrabGame** [comment]
hmmm

**Comment by CrabGame** [comment]
is it any plugin thats pwi can't work with?

**Comment by CrabGame** [comment]
i will try to reintall the plugin again

**Comment by CrabGame** [comment]
na same error

**Comment by CrabGame** [comment]
so you don't know that error

**Comment by Gnat008** [comment]
You never told me if there are any errors on startup. That is the only way for this to be possible.

**Comment by CrabGame** [comment]
i will check

**Comment by CrabGame** [comment]
Sir i when i start up it's an error:

ERROR]: Error occurred while enabling PerWorldInventory v1.11.2 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[?:?]
        at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[?:?]
        at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[?:?]
        at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[?:?]
        at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[?:?]
        at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:197) ~[?:?]
        at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins%20v1.1.0.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigotUpdate.jar:git-Spigot-4bd94dc-c765646]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 21 more

**Comment by Gnat008** [comment]
Ah, you're using Java 9. PWI is currently not compatible with that version of Java. See #260 
/cc @ljacqu

**Comment by CrabGame** [comment]
so how do i fix it?

**Comment by Gnat008** [comment]
Currently you would have to uninstall Java 9, and install Java 8.

**Comment by CrabGame** [comment]
ok
i understand Sir
Much thanks for your help

**Comment by CrabGame** [comment]
so i just need to change to java 8

**Comment by CrabGame** [comment]
that easy?

**Comment by Gnat008** [comment]
Correct.

**Comment by CrabGame** [comment]
ok please chat to me when it works with java 9

**Comment by Gnat008** [comment]
Just keep watching #260 :)
You can subscribe to it to get email notifications.

**Comment by CrabGame** [comment]
yes

**Comment by CrabGame** [comment]
it works

**Comment by ljacqu** [comment]
@Gnat008 As mentioned in #260, I cannot reproduce this. I'll give it a try again today but imho this shouldn't happen with the new injector version
