### ISSUE TITLE
[Java 10] NoClassDefFoundError: javax/annotation/PostConstruct

### ISSUE THREAD

**Issue by mibby** [Gnat008/PerWorldInventory#318]
PerWorldInventory v1.11.5
Paper dev 1403 (Spigot 1.12.2)
Java SE 10.0.1

@Gnat008 Updated my server environment to java 10 out of curiosity. Surprised to find that out of 110+ plugins, only 2 actually had issues. Figured I'd forward this to you. :)

```
[11:32:17] [Server thread/INFO]: [PerWorldInventory] Enabling PerWorldInventory v1.11.5
[11:32:17] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.11.5 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getAndValidatePostConstructMethod(PostConstructMethodInvoker.java:47) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.getPostConstructMethods(PostConstructMethodInvoker.java:34) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.handlers.postconstruct.PostConstructMethodInvoker.process(PostConstructMethodInvoker.java:23) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.InjectorImpl.runPostConstructHandlers(InjectorImpl.java:255) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.InjectorImpl.instantiate(InjectorImpl.java:182) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.InjectorImpl.get(InjectorImpl.java:155) ~[perworldinventory-1.11.5.jar:?]
	at ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:56) ~[perworldinventory-1.11.5.jar:?]
	at me.gnat008.perworldinventory.PerWorldInventory.injectServices(PerWorldInventory.java:197) ~[perworldinventory-1.11.5.jar:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:120) ~[perworldinventory-1.11.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1403]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
	... 20 more
[11:32:17] [Server thread/INFO]: [PerWorldInventory] Disabling PerWorldInventory v1.11.5
[11:32:17] [Server thread/ERROR]: Error occurred while disabling PerWorldInventory v1.11.5 (Is it up to date?)
java.lang.NullPointerException: null
	at me.gnat008.perworldinventory.PerWorldInventory.onDisable(PerWorldInventory.java:189) ~[perworldinventory-1.11.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1403]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1403]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1403]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

Java SE 8u172 doesn't output this error at start-up.

**Comment by ljacqu** [comment]
Duplicate of #316
