### ISSUE TITLE
Problem with economy

### ISSUE THREAD

**Issue by Eredrim** [Gnat008/PerWorldInventory#57]
Hello,

I have some problems with economy separation. For an unknown reason, the money accounts are increased when people pass from a world to another. I have some ideas to correct this bug : 
- Define a default world if money is set by the console
- Give chestshop money to the player's balance in world where the chestshop is.
- Search if there is an incompatibility with multiverse portals

Below the list of plugins I have can be linked to this issue : 
EssentialsEconomy, Vault, Multiverse Core, Multiverse Portals, Chestshop, Jobs Reborn, Residence Reloaded (if a residence is sold), Authme reloaded (if there is a connection problem).

Regards

**Comment by Gnat008** [comment]
You do have Vault, right?

**Comment by Eredrim** [comment]
That's right, I've forgotten do write it. I'm going to edit my first post.

**Comment by Noiknez** [comment]
I got an similar error with the option 

>   # Save and Load players' economy balances. Requires Vault!
  economy: true

enabled :

> [12:47:19] [INFO] Yonis054 issued server command: /gm 0
[12:47:19] [ERROR] Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.7.8
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:768) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:66) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:465) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:375) [EssentialsX-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NumberFormatException: For input string: "0,00"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_91]
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_91]
at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_91]
at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_91]
at org.appledash.saneeconomy.utils.NumberUtils.filterAmount(NumberUtils.java:36) ~[?:?]
at org.appledash.saneeconomy.economy.EconomyManager.subtractBalance(EconomyManager.java:104) ~[?:?]
at org.appledash.saneeconomy.vault.EconomySaneEconomy.withdrawPlayer(EconomySaneEconomy.java:157) ~[?:?]
at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getDataFromCache(PWIPlayerManager.java:208) ~[?:?]
at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:137) ~[?:?]
at me.gnat008.perworldinventory.listeners.player.PlayerGameModeChangeListener.onPlayerGameModeChange(PlayerGameModeChangeListener.java:64) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
... 24 more

**Comment by Eredrim** [comment]
I found the origin of the problem. With multiverse core, you must be aware to disable the options "bedrespawn" and "respawnworld", otherwise players can respawn in other worlds and, in this case, their accounts are summed.
However, it would be great to develop the two first points evoked in the first message.

**Comment by Gnat008** [comment]
Gonna mark as invalid then since the issue was with MV (I guess?).

As to the other points, that should be the job of an economics plugin, not PWI. This plugin only cares about things when people are changing worlds.

**Comment by Oruss7** [comment]
This issue occurs when player crash on a world with different inv/money/exp and when he come back another world, he have his account added instead of switched.

**Comment by HopeIce** [comment]
Im having an issue with switching worlds, when they switch between a creative and survivasl world it seems the survival balance is doubled. Im not sure what to alter or even attempt to do to fix this issue
