### ISSUE TITLE
Error ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by Worivee** [Gnat008/PerWorldInventory#59]
Hi, at the moment of start my serveur, your plugin say that:

[18:50:23] [Server thread/ERROR]: Error occurred while enabling PerWorldInventory v1.7.6 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 2
	at me.gnat008.perworldinventory.PerWorldInventory.checkServerVersion(PerWorldInventory.java:226) ~[?:?]
	at me.gnat008.perworldinventory.PerWorldInventory.onEnable(PerWorldInventory.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:745) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.Bukkit.reload(Bukkit.java:539) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

What is the problem ? :/

**Comment by Gnat008** [comment]
Updating Spigot past 1.9.0 (to say, 1.9.4) would work as a temporary workaround until the next release.

**Comment by Gnat008** [comment]
Fix released on Spigot. Could you confirm this is fixed on your end?

**Comment by Gnat008** [comment]
Going to assume this is resolved. If it is not, please reopen.
