### ISSUE TITLE
java.lang.NullPointerException in V1.7.7

### ISSUE THREAD

**Issue by Rocologo** [Gnat008/PerWorldInventory#66]
[21:41:35] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to PerWorldInventory v1.7.7
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.PlayerList.disconnect(PlayerList.java:385) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1061) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.NetworkManager.handleDisconnection(NetworkManager.java:318) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:174) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:832) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at me.gnat008.perworldinventory.listeners.player.PlayerQuitListener.onPlayerQuit(PlayerQuitListener.java:69) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-a9631d2-67b2424]
	... 12 more

**Comment by sigmaroot** [comment]
Confirmed. Same here. Also PlayerSpawnLocationEvent:

http://pastebin.com/ivXBJGS6

**Comment by jewome62** [comment]
+1

**Comment by Gnat008** [comment]
Fix released on Spigot. Could you confirm this is fixed on your end?

**Comment by jewome62** [comment]
Hello,

It's work for me. I haven't no more exception when i disconnect

Thanks

**Comment by Rocologo** [comment]
It works for me too. Thanks
