### ISSUE TITLE
Nullpointer while converting

### ISSUE THREAD

**Issue by B1acksheep** [Gnat008/PerWorldInventory#67]
```
[22:42:04 WARN]: [PerWorldInventory] Error importing inventory for player: null For group: default For gamemode: SURVIVAL
[22:42:04 WARN]: java.lang.IllegalArgumentException: Name cannot be null
[22:42:04 WARN]:        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[22:42:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.getOfflinePlayer(CraftServer.java:1289)
[22:42:04 WARN]:        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:745)
[22:42:04 WARN]:        at com.onarandombox.multiverseinventories.util.data.DefaultPlayerProfile.<init>(DefaultPlayerProfile.java:51)
[22:42:04 WARN]:        at com.onarandombox.multiverseinventories.util.data.FlatFilePlayerData.getPlayerData(FlatFilePlayerData.java:283)
[22:42:04 WARN]:        at com.onarandombox.multiverseinventories.WeakProfileContainer.getPlayerData(WeakProfileContainer.java:98)
[22:42:04 WARN]:        at me.gnat008.perworldinventory.data.DataConverter.convertMultiVerseData(DataConverter.java:92)
[22:42:04 WARN]:        at me.gnat008.perworldinventory.commands.PerWorldInventoryCommand$1.run(PerWorldInventoryCommand.java:215)
[22:42:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[22:42:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:42:04 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[22:42:04 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[22:42:04 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Gnat008** [comment]
Unsure if this is actually a bug with PWI, or MV-I...

**Comment by B1acksheep** [comment]
It happens during converting.
An Information, who now has lost his inventory would be a start...

**Comment by B1acksheep** [comment]
We have found the reason.
It converts only people who have logged in since the Multiverse-Inv version with UUID support is running.

I think, you could catch the error and inform the plugin users about this.
