### ISSUE TITLE
Can't seem to get the plugin to work

### ISSUE THREAD

**Issue by SuperSharpBlue** [Gnat008/PerWorldInventory#8]
After installing this plugin and trying to test it, I get this error and the inventory stays the same across all worlds.

[14:50:32] [Server thread/INFO]: SuperSharpBlue issued server command: /mvtp plotworld
[14:50:32] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to SeparateWorldInventories v2.5.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:580) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.teleport(CraftPlayer.java:477) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.teleport(CraftEntity.java:204) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897) [Multiverse-Core-2.5.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.getItemFlags()Ljava/util/Set;
at com.ExtendedAlpha.SWI.SeparatorLib.SingleItemSeparator.serializeItems(SingleItemSeparator.java:78) ~[?:?]
at com.ExtendedAlpha.SWI.SeparatorLib.SingleItemSeparator.serializeItemInInventory(SingleItemSeparator.java:27) ~[?:?]
at com.ExtendedAlpha.SWI.SeparatorLib.InventorySeparator.serializeInventory(InventorySeparator.java:29) ~[?:?]
at com.ExtendedAlpha.SWI.SeparatorLib.PlayerSeparator.serializePlayer(PlayerSeparator.java:22) ~[?:?]
at com.ExtendedAlpha.SWI.Listeners.ChangedWorldEventListener.onPlayerChangeWorld(ChangedWorldEventListener.java:41) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
... 28 more

**Comment by SuperSharpBlue** [comment]
config.yml

first-start: false
manage-gamemodes: false
separate-gamemode-inventories: false
player:
  ender-chest: true
  inventory: true
  stats: true
player-stats:
  can-fly: true
  display-name: false
  exhaustion: true
  exp: true
  food: true
  flying: true
  gamemode: false
  health: true
  level: true
  potion-effects: true
  saturation: true

**Comment by SuperSharpBlue** [comment]
worlds.yml

groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
  plots:
    - plotworld
    default-gamemode: CREATIVE

**Comment by Gnat008** [comment]
My plugin appears no where in that stacktrace, however 'SeparateWorldInventories' does. Those are my config files, however. Do you have both plugins installed?

**Comment by SuperSharpBlue** [comment]
Yea, I tried using SeperateWorldInventories but couldn't get it to work, I forgot to delete the jar file. Now I have it removed completely and I am getting the following error:

[11:12:54] [Server thread/INFO]: SuperSharpBlue issued server command: /mvtp world
[11:12:54] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to PerWorldInventory v1.4.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerList.moveToWorld(PlayerList.java:580) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.teleport(CraftPlayer.java:477) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.entity.CraftEntity.teleport(CraftEntity.java:204) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.teleport(SimpleSafeTTeleporter.java:335) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.commands.TeleportCommand.runCommand(TeleportCommand.java:163) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143) [Multiverse-Core-2.5.jar:?]
at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93) [Multiverse-Core-2.5.jar:?]
at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:897) [Multiverse-Core-2.5.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.getItemFlags()Ljava/util/Set;
at com.kill3rtaco.tacoserialization.SingleItemSerialization.serializeItems(SingleItemSerialization.java:89) ~[?:?]
at com.kill3rtaco.tacoserialization.SingleItemSerialization.serializeItemInInventory(SingleItemSerialization.java:33) ~[?:?]
at com.kill3rtaco.tacoserialization.InventorySerialization.serializeInventory(InventorySerialization.java:41) ~[?:?]
at com.kill3rtaco.tacoserialization.PlayerSerialization.serializePlayer(PlayerSerialization.java:34) ~[?:?]
at me.gnat008.perworldinventory.listeners.PlayerChangedWorldListener.onPlayerChangeWorld(PlayerChangedWorldListener.java:55) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[minecraft_server.jar:git-Spigot-d6b5ba7-606cf0e]
... 28 more

**Comment by Gnat008** [comment]
Your Spigot version is 247 versions behind. This happened to another person with a Spigot that was ~130 versions behind. Can you please try updating Spigot?

**Comment by SuperSharpBlue** [comment]
Yup, that seemed to work. Didn't realize we were so far behind!
