### ISSUE TITLE
Null pointers at runtime

### ISSUE THREAD

**Issue by Noket** [Gnat008/PerWorldInventory#98]
`[13:05:42] [Craft Scheduler Thread - 65/WARN]: Exception in thread "Craft Scheduler Thread - 65" 
[13:05:42] [Craft Scheduler Thread - 61/WARN]: Exception in thread "Craft Scheduler Thread - 61" 
[13:05:42] [Craft Scheduler Thread - 61/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.1 generated an exception while executing task 4861
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:227)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:93)
    at me.gnat008.perworldinventory.data.FileWriter$1.run(FileWriter.java:83)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[13:05:42] [Craft Scheduler Thread - 62/WARN]: Exception in thread "Craft Scheduler Thread - 62" 
[13:05:42] [Craft Scheduler Thread - 62/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.1 generated an exception while executing task 4859
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:227)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:93)
    at me.gnat008.perworldinventory.data.FileWriter$1.run(FileWriter.java:83)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[13:05:42] [Craft Scheduler Thread - 68/WARN]: Exception in thread "Craft Scheduler Thread - 68" 
[13:05:42] [Server thread/INFO]: Saving...
[13:05:42] [Craft Scheduler Thread - 68/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.1 generated an exception while executing task 4857
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:227)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:93)
    at me.gnat008.perworldinventory.data.FileWriter$1.run(FileWriter.java:83)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[13:05:42] [Craft Scheduler Thread - 66/WARN]: Exception in thread "Craft Scheduler Thread - 66" 
[13:05:42] [Craft Scheduler Thread - 66/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.1 generated an exception while executing task 4858
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:227)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:93)
    at me.gnat008.perworldinventory.data.FileWriter$1.run(FileWriter.java:83)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[13:05:42] [Craft Scheduler Thread - 65/WARN]: org.apache.commons.lang.UnhandledException: Plugin PerWorldInventory v1.8.1 generated an exception while executing task 4860
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at me.gnat008.perworldinventory.data.FileWriter.getFile(FileWriter.java:227)
    at me.gnat008.perworldinventory.data.FileWriter.saveToDatabase(FileWriter.java:93)
    at me.gnat008.perworldinventory.data.FileWriter$1.run(FileWriter.java:83)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

[13:05:43] [Server thread/INFO]: Saved the world`

**Comment by Noket** [comment]
Running git-Spigot-8a048fe-5ff377a (MC: 1.9.4) (Implementing API ver 1.9.4-R0.1-SNAPSHOT)

**Comment by Gnat008** [comment]
Could you turn on debug mode in the config, switch worlds, then log out? This should produce the error as well as maybe something helpful so I can track down what's going wrong. Then attach your server.log file.

**Comment by Noket** [comment]
Unfortunately, I think the bug was a result of the default configuration.
We can't revert without making many players very angry.

We had the old multiverse inventories plugin. I tried importing the old
json database into PWI. PWI was still having problems and throwing this
error. When I cracked open the config, the config (worlds) only showed the
default minecraft world names. We don't even have the default worlds on our
server.

I'll see about getting more detailed logs tomorrow. I'll have to regex out
all the ips and whatnot

On Sep 4, 2016 4:23 PM, "Gnat008" <notifications@github.com> wrote:
>
> Could you turn on debug mode in the config, switch worlds, then log out?
This should produce the error as well as maybe something helpful so I can
track down what's going wrong. Then attach your server.log file.

**Comment by Gnat008** [comment]
The worlds.yml file is something you have to configure. How did you import? By moving the files?

**Comment by ljacqu** [comment]
@Gnat008 Looking at this and similar reports, I think this happens when no `Group` can be returned for a player. (`GroupManager#getGroup()` is called in `PWIPlayerManager#scheduleRepeatingTask()`, and its result is passed to `FileWriter` without checking if the group is `null`.)

**Comment by Gnat008** [comment]
Thanks, I'll look into that when I can. Just moved, and won't have internet til next Tuesday.

**Comment by Gnat008** [comment]
See #115, this should now be fixed.
