### ISSUE TITLE
Multiple issues (MV-inv conversion, gamemodes changing issues, world changing issues...)

### ISSUE THREAD

**Issue by elFlashor** [Gnat008/PerWorldInventory#99]
- I tried a basic conversion from MV-inv (only 3 users, 2 worlds with creative & survival inventories for each), and right after the conversion, changing gamemodes gave me that error:
`[09:00:23] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to PerWorldInventory v1.8.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:66) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Not a JSON Object: null
    at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at me.gnat008.perworldinventory.data.FileWriter.getFromDatabase(FileWriter.java:145) ~[?:?]
    at me.gnat008.perworldinventory.data.players.PWIPlayerManager.getPlayerData(PWIPlayerManager.java:155) ~[?:?]
    at me.gnat008.perworldinventory.process.GameModeChangeProcess.processGameModeChange(GameModeChangeProcess.java:58) ~[?:?]
    at me.gnat008.perworldinventory.listeners.player.PlayerGameModeChangeListener.onPlayerGameModeChange(PlayerGameModeChangeListener.java:39) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    ... 24 more`

- Restarting the server seemed to gave me the correct inventories in the main world, both survival & creative
- Switching to another world (non shared inventory world) gave me an empty inventory (whereas I had items in MV-inv)
- Switching to creative then back to survival in that world gave me my other world (???) survival inventory
- When I switch between creative & survival, half of the time the inventory I have in my hands get carried to the other gamemode... and sometimes not... Seems rather random and buggy?

- It seems the plugin created a folder named "data" + my UUID... Missing "/" maybe? Isn't that supposed to be tested...?

- Edit: after restarting the server (another time), changing gamemodes between survival & creative seems to cycle between 3 (wtf?) different inventories: my survival, my creative, and the survival of my other world... How is that even possible?

Spigot: 1.8.8, 1.9, 1.10.2... Seems to happen with all the spigot versions.
Pretty much default configs.

config:

> config-version: 4
manage-gamemodes: false
separate-gamemode-inventories: true
share-if-unconfigured: false
player:
  economy: false
  ender-chest: true
  inventory: true
  stats:
    can-fly: true
    display-name: false
    exhaustion: true
    exp: true
    food: true
    flying: true
    gamemode: false
    health: true
    level: true
    potion-effects: true
    saturation: true
    fall-distance: true
    fire-ticks: true
    max-air: true
    remaining-air: true
save-interval: 300
load-data-on-join: false
debug-mode: false
disable-bypass: false

worlds:

> groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL

EDIT: Sorry for the formatting, yaml comments got way bigger than expected...

**Comment by Gnat008** [comment]
They were tested, and it worked on my server. Sometimes I'm not sure how it works, as it shouldn't, but...

As for the random inventory issues, if that isn't caused by the file path (was only for the last logout data anyway), you did remove MultiVerse-Inventories, right? This sounds just like what would happen if it was accidentally left in.

**Comment by elFlashor** [comment]
Bah, very sorry for that, indeed it was that I forgot to remove MultiVerse-Inventories... It's probably a very sad and common mistake here, as it says in the console it is deactivated, I'm sure most of people just forgot to remove it from the folder...

While testing further (this time after removing MV-inv ^^) I found 2 other bugs, one with an error log and another related to items imported with MV-inv that have color in their name and lore.
Should I add them here or do you prefer me opening another ticket?

**Comment by Gnat008** [comment]
Err Yeah, if you could put those in separate tickets, that would be great! Since I guess they're unrelated to this one?
